version: "3"
services:
  # Front facing Nginx reverse proxy server
  reverse-proxy:
    # maybe switch to alpine image in the end
    image: nginx:1.18.0
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse_proxy/placeholder_public:/usr/share/nginx/html/
      - ./reverse_proxy/dhparam:/etc/ssl/certs
      - ./reverse_proxy/nginx-conf:/etc/nginx/conf.d
      - ./ssl/certbot-etc:/etc/letsencrypt
      - ./ssl/certbot-var:/var/lib/letsencrypt
    networks:
      - frontend
      - backend

  # letsencrypt free SSL crtificates
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./reverse_proxy/placeholder_public:/usr/share/nginx/html/
      - ./ssl/certbot-etc:/etc/letsencrypt
      - ./ssl/certbot-var:/var/lib/letsencrypt
    depends_on:
      - reverse-proxy
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/ --email denisnv@userstories.dev --agree-tos --no-eff-email --keep-until-expiring --expand -d userstories.dev  -d www.userstories.dev -d backend.userstories.dev -d auth.userstories.dev
    # command: certonly --webroot --webroot-path=/usr/share/nginx/html/ --email denisnv@userstories.dev --agree-tos --no-eff-email --keep-until-expiring --staging --expand -d userstories.dev  -d www.userstories.dev -d backend.userstories.dev -d auth.userstories.dev
    networks:
      - backend

  # # Database, sgared between keycloak and wordpress
  # mysqldb:
  #   container_name: wysiblocks_mysqldb
  #   restart: unless-stopped
  #   image: mysql:5.7
  #   volumes:
  #     - mysqldbdata:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=user_stories_root
  #     - MYSQL_DATABASE=keycloak
  #     - MYSQL_USER=keycloak
  #     - MYSQL_PASSWORD=user_stories_keycloak
  #   networks:
  #     - backend

  # # Standalone authentication server
  # keycloak:
  #   container_name: wysiblocks_keycloak
  #   restart: unless-stopped
  #   depends_on:
  #     - mysqldb
  #   image: denisnv/wysiblocks_keycloak:latest
  #   volumes:
  #     - ./keycloak_exports/wysiblocks_realm.json:/tmp/wysiblocks_realm.json
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - KEYCLOAK_USER=user_stories
  #     - KEYCLOAK_PASSWORD=user_stories_root
  #     - DB_VENDOR=mysql
  #     - DB_ADDR=mysqldb
  #     - DB_DATABASE=keycloak
  #     - DB_USER=keycloak
  #     - DB_PASSWORD=user_stories_keycloak
  #     - KEYCLOAK_IMPORT=/tmp/wysiblocks_realm.json
  #   networks:
  #     - backend

  # Database, sgared between strapi and core API
  mongodb:
    image: mongo:4.2.6-bionic
    container_name: wysiblocks_mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user_stories
      - MONGO_INITDB_ROOT_PASSWORD=user_stories_root
      - MONGODB_DATA_DIR=/data/db
      - MONGODB_LOG_DIR=/dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend
    # This is only required for connecting to the remote db from another origin
    # ports:
    #   - 27017:27017

  # Open source Headless CMS with customizable APIs
  strapi_cms:
    container_name: wysiblocks_strapi_cms
    restart: unless-stopped
    depends_on:
      - mongodb
    image: denisnv/wysiblocks_strapi_cms:latest
    volumes:
      - strapi_public:/app/public/
    ports:
      - "1337:1337"
    environment:
      - DATABASE_HOST=mongodb
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi_cms
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=user_stories_strapi
      - AUTHENTICATION_DATABASE=strapi_cms
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  mysqldbdata:
    driver: local
  strapi_public:
    driver: local
